
import { CropInfo } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: "KrishiBondhu AI",
    greeting: "Welcome",
    weather: "Weather",
    scanPlant: "Scan Plant",
    chatAssistant: "Agri Chat",
    cropCalendar: "Crops",
    loans: "Loans",
    identifyDisease: "Identify Disease",
    takePhoto: "Take Photo",
    analyzing: "Analyzing...",
    askAnything: "Ask about crops, pests...",
    send: "Send",
    loadingWeather: "Loading weather...",
    locationError: "Location access needed",
    temp: "Temp",
    wind: "Wind",
    diseaseDetected: "Analysis Result",
    remedy: "Remedy",
    uploadImage: "Upload Image",
    noImageSelected: "No image selected",
    switchLang: "বাংলা",
    offline: "You are offline. Showing saved data.",
    shareResult: "Share Results",
    // Loan Tracker
    loanTracker: "Loan Tracker",
    totalDebt: "Total Active Debt",
    totalPaid: "Total Repaid",
    addLoan: "Add New Loan",
    editLoan: "Edit Loan",
    lenderName: "Lender Name",
    amount: "Amount (Tk)",
    dueDate: "Due Date",
    startDate: "Start Date",
    markPaid: "Mark Paid",
    markActive: "Mark Active",
    status: "Status",
    active: "Active",
    paid: "Paid",
    activeLoans: "Active Loans",
    history: "History",
    saveLoan: "Save Loan",
    cancel: "Cancel",
    noLoans: "No loans found. Add your first loan!",
    delete: "Delete",
    loanDetails: "Loan Details",
    notes: "Notes",
    close: "Close",
    selectPaymentMethod: "Select Payment Method",
    // Payment Flow
    payWithBkash: "Pay with bKash",
    payWithBank: "Pay with Bank",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    enterPin: "Enter PIN",
    confirm: "Confirm Payment",
    processing: "Processing...",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    transactionId: "TrxID",
    retryPayment: "Retry Payment",
    goBack: "Go Back",
    merchant: "Merchant",
    invoice: "Invoice No",
    insufficientFunds: "Insufficient funds or wrong PIN",
    // Reminders
    setReminder: "Set Reminder",
    reminderSet: "Reminder set successfully",
    permissionDenied: "Please enable notifications in your browser settings",
    fertilizer: "Fertilizer",
    addFertilizerReminder: "Add Fertilizer Reminder",
    reminderDate: "Reminder Date",
    reminderType: "Type (e.g. Urea)",
    save: "Save",
    fertilizerFor: "Fertilizer for",
    loanDue: "Loan Repayment Due",
    upcomingReminders: "Upcoming Reminders",
    noReminders: "No upcoming reminders",
    // Auth
    login: "Login",
    register: "Sign Up",
    phoneOrEmail: "Mobile Number (e.g., 017...)",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    loginSuccess: "Login Successful",
    logout: "Logout",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    invalidPhone: "Invalid BD Mobile Number",
    fillAllFields: "Please fill all fields",
    userExists: "User already exists",
    wrongCredentials: "Wrong mobile number or password",
    passwordsDontMatch: "Passwords do not match",
    welcomeBack: "Welcome back",
    createAccount: "Create Account",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendOtp: "Send OTP",
    enterOtp: "Enter OTP (1234)",
    newPassword: "New Password",
    verify: "Verify",
    otpSent: "OTP sent to your mobile",
    userNotFound: "User not found",
    passwordResetSuccess: "Password reset successfully",
    biometricLogin: "Login with Biometrics",
    biometricFailed: "Biometric authentication failed",
    // Profile
    profile: "Profile",
    editProfile: "Edit Profile",
    location: "Location",
    saveChanges: "Save Changes",
    // Scanner
    placeInFrame: "Place crop within the frame",
    // Crop
    searchCrops: "Search crops...",
    idealConditions: "Ideal Conditions",
    commonIssues: "Common Issues",
    growthDuration: "Growth Duration",
  },
  bn: {
    appTitle: "কৃষিবন্ধু এআই",
    greeting: "স্বাগতম",
    weather: "আবহাওয়া",
    scanPlant: "রোগ নির্ণয়",
    chatAssistant: "সহকারী",
    cropCalendar: "ফসল",
    loans: "ঋণ",
    identifyDisease: "রোগ শনাক্ত করুন",
    takePhoto: "ছবি তুলুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    askAnything: "ফসল বা রোগ সম্পর্কে জিজ্ঞাসা করুন...",
    send: "পাঠান",
    loadingWeather: "আবহাওয়া লোড হচ্ছে...",
    locationError: "অবস্থান অনুমতি প্রয়োজন",
    temp: "তাপমাত্রা",
    wind: "বাতাস",
    diseaseDetected: "বিশ্লেষণের ফলাফল",
    remedy: "প্রতিকার",
    uploadImage: "ছবি আপলোড করুন",
    noImageSelected: "কোন ছবি নির্বাচিত হয়নি",
    switchLang: "English",
    offline: "আপনি অফলাইনে আছেন। সংরক্ষিত তথ্য দেখানো হচ্ছে।",
    shareResult: "ফলাফল শেয়ার করুন",
    // Loan Tracker
    loanTracker: "ঋণ ব্যবস্থাপনা",
    totalDebt: "মোট বর্তমান ঋণ",
    totalPaid: "মোট পরিশোধিত",
    addLoan: "নতুন ঋণ যোগ করুন",
    editLoan: "ঋণ সম্পাদনা",
    lenderName: "ঋণদাতার নাম",
    amount: "টাকার পরিমাণ",
    dueDate: "পরিশোধের তারিখ",
    startDate: "নেওয়ার তারিখ",
    markPaid: "পরিশোধিত",
    markActive: "অপরিবর্তিত",
    status: "অবস্থা",
    active: "চলমান",
    paid: "পরিশোধিত",
    activeLoans: "চলমান ঋণ",
    history: "ইতিহাস",
    saveLoan: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    noLoans: "কোন ঋণ নেই। আপনার প্রথম ঋণ যোগ করুন!",
    delete: "মুছে ফেলুন",
    loanDetails: "ঋণের বিবরণ",
    notes: "নোট",
    close: "বন্ধ করুন",
    selectPaymentMethod: "পেমেন্ট মাধ্যম নির্বাচন করুন",
    // Payment Flow
    payWithBkash: "বিকাশ পেমেন্ট",
    payWithBank: "ব্যাংক পেমেন্ট",
    bankName: "ব্যাংকের নাম",
    accountNumber: "অ্যাকাউন্ট নম্বর",
    enterPin: "পিন নম্বর দিন",
    confirm: "পেমেন্ট নিশ্চিত করুন",
    processing: "প্রক্রিয়াধীন...",
    paymentSuccess: "পেমেন্ট সফল হয়েছে!",
    paymentFailed: "পেমেন্ট ব্যর্থ হয়েছে",
    transactionId: "TrxID",
    retryPayment: "আবার চেষ্টা করুন",
    goBack: "ফিরে যান",
    merchant: "মার্চেন্ট",
    invoice: "ইনভয়েস নং",
    insufficientFunds: "অপর্যাপ্ত ব্যালেন্স বা ভুল পিন",
    // Reminders
    setReminder: "রিমাইন্ডার দিন",
    reminderSet: "রিমাইন্ডার সেট করা হয়েছে",
    permissionDenied: "দয়া করে ব্রাউজারে নোটিফিকেশন চালু করুন",
    fertilizer: "সার",
    addFertilizerReminder: "সারের রিমাইন্ডার যোগ করুন",
    reminderDate: "তারিখ",
    reminderType: "ধরন (যেমন: ইউরিয়া)",
    save: "সংরক্ষণ",
    fertilizerFor: "সার প্রয়োগ:",
    loanDue: "ঋণ পরিশোধের সময়",
    upcomingReminders: "আসন্ন রিমাইন্ডার",
    noReminders: "কোন রিমাইন্ডার নেই",
    // Auth
    login: "লগইন",
    register: "নিবন্ধন করুন",
    phoneOrEmail: "মোবাইল নম্বর (যেমন: ০১৭...)",
    password: "পাসওয়ার্ড",
    confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
    fullName: "পুরো নাম",
    loginSuccess: "লগইন সফল হয়েছে",
    logout: "লগআউট",
    dontHaveAccount: "অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "অ্যাকাউন্ট আছে?",
    invalidPhone: "ভুল মোবাইল নম্বর",
    fillAllFields: "সব তথ্য পূরণ করুন",
    userExists: "এই নম্বরে অ্যাকাউন্ট আছে",
    wrongCredentials: "ভুল নম্বর বা পাসওয়ার্ড",
    passwordsDontMatch: "পাসওয়ার্ড মিলছে না",
    welcomeBack: "স্বাগতম",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    resetPassword: "পাসওয়ার্ড রিসেট",
    sendOtp: "ওটিপি পাঠান",
    enterOtp: "ওটিপি দিন (1234)",
    newPassword: "নতুন পাসওয়ার্ড",
    verify: "যাচাই করুন",
    otpSent: "আপনার মোবাইলে ওটিপি পাঠানো হয়েছে",
    userNotFound: "ব্যবহারকারী খুঁজে পাওয়া যায়নি",
    passwordResetSuccess: "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে",
    biometricLogin: "বায়োমেট্রিক লগইন",
    biometricFailed: "বায়োমেট্রিক শনাক্তকরণ ব্যর্থ হয়েছে",
    // Profile
    profile: "প্রোফাইল",
    editProfile: "প্রোফাইল সম্পাদনা",
    location: "অবস্থান",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    // Scanner
    placeInFrame: "শস্য ফ্রেমের মধ্যে রাখুন",
    // Crop
    searchCrops: "ফসল খুঁজুন...",
    idealConditions: "উপযুক্ত পরিবেশ",
    commonIssues: "সাধারণ রোগবালাই",
    growthDuration: "জীবনকাল",
  }
};

export const CROPS: CropInfo[] = [
  {
    id: '1',
    nameEn: 'Rice (Boro)',
    nameBn: 'ধান (বোরো)',
    season: 'Robi',
    plantingTime: 'Dec - Feb',
    harvestTime: 'Apr - May',
    image: 'https://images.unsplash.com/photo-1599940778173-e276d4acb2be?auto=format&fit=crop&q=80&w=400',
    idealTemp: '20°C - 30°C',
    soilType: 'Clay or Clay Loam',
    commonDiseases: ['Blast', 'Bacterial Blight'],
    growthDuration: '140-155 Days'
  },
  {
    id: '2',
    nameEn: 'Jute',
    nameBn: 'পাট',
    season: 'Kharif-1',
    plantingTime: 'Mar - Apr',
    harvestTime: 'Jul - Aug',
    image: 'https://images.unsplash.com/photo-1616428780721-a3f5a0c32608?auto=format&fit=crop&q=80&w=400',
    idealTemp: '24°C - 35°C',
    soilType: 'Alluvial Soil',
    commonDiseases: ['Stem Rot', 'Mosaic Virus'],
    growthDuration: '120 Days'
  },
  {
    id: '3',
    nameEn: 'Potato',
    nameBn: 'আলু',
    season: 'Robi',
    plantingTime: 'Nov - Dec',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=400',
    idealTemp: '15°C - 20°C',
    soilType: 'Sandy Loam',
    commonDiseases: ['Late Blight', 'Scab'],
    growthDuration: '90-100 Days'
  },
  {
    id: '4',
    nameEn: 'Mango',
    nameBn: 'আম',
    season: 'Summer',
    plantingTime: 'Jun - Jul',
    harvestTime: 'May - Jul',
    image: 'https://images.unsplash.com/photo-1627885060699-0d3221975e53?auto=format&fit=crop&q=80&w=400',
    idealTemp: '24°C - 30°C',
    soilType: 'Deep Loam',
    commonDiseases: ['Anthracnose', 'Powdery Mildew'],
    growthDuration: 'Perennial'
  },
  {
    id: '5',
    nameEn: 'Wheat',
    nameBn: 'গম',
    season: 'Robi',
    plantingTime: 'Nov - Dec',
    harvestTime: 'Mar - Apr',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
    idealTemp: '15°C - 25°C',
    soilType: 'Loam',
    commonDiseases: ['Rust', 'Blast'],
    growthDuration: '100-110 Days'
  },
  {
    id: '6',
    nameEn: 'Mustard',
    nameBn: 'সরিষা',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Jan - Feb',
    image: 'https://images.unsplash.com/photo-1506543730500-1738e9a25b24?auto=format&fit=crop&q=80&w=400',
    growthDuration: '80-90 Days'
  },
  {
    id: '7',
    nameEn: 'Lentil',
    nameBn: 'মসুর ডাল',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&q=80&w=400',
    growthDuration: '100-110 Days'
  },
  {
    id: '8',
    nameEn: 'Brinjal',
    nameBn: 'বেগুন',
    season: 'Robi/Kharif',
    plantingTime: 'Sep - Oct',
    harvestTime: 'Dec - Jan',
    image: 'https://images.unsplash.com/photo-1615485925763-867862f80c55?auto=format&fit=crop&q=80&w=400',
    growthDuration: '130-150 Days'
  },
  {
    id: '9',
    nameEn: 'Onion',
    nameBn: 'পেঁয়াজ',
    season: 'Robi',
    plantingTime: 'Dec - Jan',
    harvestTime: 'Mar - Apr',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=400',
    growthDuration: '100-120 Days'
  },
  {
    id: '10',
    nameEn: 'Tomato',
    nameBn: 'টমেটো',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=400',
    growthDuration: '90-100 Days'
  }
];

export const SYSTEM_INSTRUCTION_CHAT = `You are KrishiBondhu, a helpful agricultural AI assistant for farmers in Bangladesh. 
Your goal is to help with pest control, disease identification, crop advice, and weather interpretation.
1. Always answer in the language the user asks (Bengali or English).
2. Keep answers simple, practical, and concise (easy to read for low literacy).
3. If asked about prices, say you don't have real-time market data but can give general trends.
4. Use emoji where appropriate to make it friendly.
5. If the user greets you, greet them warmly as a friend of the farmer.`;

export const SYSTEM_INSTRUCTION_VISION = `You are an expert plant pathologist for Bangladeshi crops.
1. Analyze the image for plant diseases or pests common in South Asia.
2. If a disease is found, state the name (in Bengali and English).
3. Provide 2-3 practical, organic, or chemical remedies available in Bangladesh.
4. If the image is not a plant, strictly say "Please upload a clear photo of a plant or crop."
5. Format the output as Markdown.`;
