
import { CropInfo } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: "KrishiBondhu AI",
    greeting: "Welcome, Farmer",
    weather: "Weather",
    scanPlant: "Scan Plant",
    chatAssistant: "Agri Chat",
    cropCalendar: "Crops",
    loans: "Loans",
    identifyDisease: "Identify Disease",
    takePhoto: "Take Photo",
    analyzing: "Analyzing...",
    askAnything: "Ask about crops, pests...",
    send: "Send",
    loadingWeather: "Loading weather...",
    locationError: "Location access needed",
    temp: "Temp",
    wind: "Wind",
    diseaseDetected: "Analysis Result",
    remedy: "Remedy",
    uploadImage: "Upload Image",
    noImageSelected: "No image selected",
    switchLang: "বাংলা",
    // Loan Tracker
    loanTracker: "Loan Tracker",
    totalDebt: "Total Active Debt",
    totalPaid: "Total Repaid",
    addLoan: "Add New Loan",
    editLoan: "Edit Loan",
    lenderName: "Lender Name",
    amount: "Amount (Tk)",
    dueDate: "Due Date",
    startDate: "Start Date",
    markPaid: "Mark Paid",
    markActive: "Mark Active",
    status: "Status",
    active: "Active",
    paid: "Paid",
    activeLoans: "Active Loans",
    history: "History",
    saveLoan: "Save Loan",
    cancel: "Cancel",
    noLoans: "No loans found.",
    delete: "Delete",
    loanDetails: "Loan Details",
    notes: "Notes",
    close: "Close",
    // Reminders
    setReminder: "Set Reminder",
    reminderSet: "Reminder set successfully",
    permissionDenied: "Please enable notifications in your browser settings",
    fertilizer: "Fertilizer",
    addFertilizerReminder: "Add Fertilizer Reminder",
    reminderDate: "Reminder Date",
    reminderType: "Type (e.g. Urea)",
    save: "Save",
    fertilizerFor: "Fertilizer for",
    loanDue: "Loan Repayment Due",
    upcomingReminders: "Upcoming Reminders",
    noReminders: "No upcoming reminders"
  },
  bn: {
    appTitle: "কৃষিবন্ধু এআই",
    greeting: "স্বাগতম, কৃষক বন্ধু",
    weather: "আবহাওয়া",
    scanPlant: "রোগ নির্ণয়",
    chatAssistant: "সহকারী",
    cropCalendar: "ফসল",
    loans: "ঋণ",
    identifyDisease: "রোগ শনাক্ত করুন",
    takePhoto: "ছবি তুলুন",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    askAnything: "ফসল বা রোগ সম্পর্কে জিজ্ঞাসা করুন...",
    send: "পাঠান",
    loadingWeather: "আবহাওয়া লোড হচ্ছে...",
    locationError: "অবস্থান অনুমতি প্রয়োজন",
    temp: "তাপমাত্রা",
    wind: "বাতাস",
    diseaseDetected: "বিশ্লেষণের ফলাফল",
    remedy: "প্রতিকার",
    uploadImage: "ছবি আপলোড করুন",
    noImageSelected: "কোন ছবি নির্বাচিত হয়নি",
    switchLang: "English",
    // Loan Tracker
    loanTracker: "ঋণ ব্যবস্থাপনা",
    totalDebt: "মোট বর্তমান ঋণ",
    totalPaid: "মোট পরিশোধিত",
    addLoan: "নতুন ঋণ যোগ করুন",
    editLoan: "ঋণ সম্পাদনা",
    lenderName: "ঋণদাতার নাম",
    amount: "টাকার পরিমাণ",
    dueDate: "পরিশোধের তারিখ",
    startDate: "নেওয়ার তারিখ",
    markPaid: "পরিশোধিত",
    markActive: "অপরিবর্তিত",
    status: "অবস্থা",
    active: "চলমান",
    paid: "পরিশোধিত",
    activeLoans: "চলমান ঋণ",
    history: "ইতিহাস",
    saveLoan: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    noLoans: "কোন ঋণ নেই।",
    delete: "মুছে ফেলুন",
    loanDetails: "ঋণের বিবরণ",
    notes: "নোট",
    close: "বন্ধ করুন",
    // Reminders
    setReminder: "রিমাইন্ডার দিন",
    reminderSet: "রিমাইন্ডার সেট করা হয়েছে",
    permissionDenied: "দয়া করে ব্রাউজারে নোটিফিকেশন চালু করুন",
    fertilizer: "সার",
    addFertilizerReminder: "সারের রিমাইন্ডার যোগ করুন",
    reminderDate: "তারিখ",
    reminderType: "ধরন (যেমন: ইউরিয়া)",
    save: "সংরক্ষণ",
    fertilizerFor: "সার প্রয়োগ:",
    loanDue: "ঋণ পরিশোধের সময়",
    upcomingReminders: "আসন্ন রিমাইন্ডার",
    noReminders: "কোন রিমাইন্ডার নেই"
  }
};

export const CROPS: CropInfo[] = [
  {
    id: '1',
    nameEn: 'Rice (Boro)',
    nameBn: 'ধান (বোরো)',
    season: 'Robi',
    plantingTime: 'Dec - Feb',
    harvestTime: 'Apr - May',
    image: 'https://images.unsplash.com/photo-1599940778173-e276d4acb2be?auto=format&fit=crop&q=80&w=400', 
  },
  {
    id: '2',
    nameEn: 'Jute',
    nameBn: 'পাট',
    season: 'Kharif-1',
    plantingTime: 'Mar - Apr',
    harvestTime: 'Jul - Aug',
    image: 'https://images.unsplash.com/photo-1616428780721-a3f5a0c32608?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '3',
    nameEn: 'Potato',
    nameBn: 'আলু',
    season: 'Robi',
    plantingTime: 'Nov - Dec',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '4',
    nameEn: 'Mango',
    nameBn: 'আম',
    season: 'Summer',
    plantingTime: 'Jun - Jul',
    harvestTime: 'May - Jul',
    image: 'https://images.unsplash.com/photo-1627885060699-0d3221975e53?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '5',
    nameEn: 'Wheat',
    nameBn: 'গম',
    season: 'Robi',
    plantingTime: 'Nov - Dec',
    harvestTime: 'Mar - Apr',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '6',
    nameEn: 'Mustard',
    nameBn: 'সরিষা',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Jan - Feb',
    image: 'https://images.unsplash.com/photo-1506543730500-1738e9a25b24?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '7',
    nameEn: 'Lentil',
    nameBn: 'মসুর ডাল',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '8',
    nameEn: 'Brinjal',
    nameBn: 'বেগুন',
    season: 'Robi/Kharif',
    plantingTime: 'Sep - Oct',
    harvestTime: 'Dec - Jan',
    image: 'https://images.unsplash.com/photo-1615485925763-867862f80c55?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '9',
    nameEn: 'Onion',
    nameBn: 'পেঁয়াজ',
    season: 'Robi',
    plantingTime: 'Dec - Jan',
    harvestTime: 'Mar - Apr',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '10',
    nameEn: 'Tomato',
    nameBn: 'টমেটো',
    season: 'Robi',
    plantingTime: 'Oct - Nov',
    harvestTime: 'Feb - Mar',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: '11',
    nameEn: 'Tea',
    nameBn: 'চা',
    season: 'Year-round',
    plantingTime: 'May - Jun',
    harvestTime: 'Weekly',
    image: 'https://images.unsplash.com/photo-1588713437158-b38466657c91?auto=format&fit=crop&q=80&w=400',
  }
];

export const SYSTEM_INSTRUCTION_CHAT = `You are KrishiBondhu, a helpful agricultural AI assistant for farmers in Bangladesh. 
Your goal is to help with pest control, disease identification, crop advice, and weather interpretation.
1. Always answer in the language the user asks (Bengali or English).
2. Keep answers simple, practical, and concise (easy to read for low literacy).
3. If asked about prices, say you don't have real-time market data but can give general trends.
4. Use emoji where appropriate to make it friendly.
5. If the user greets you, greet them warmly as a friend of the farmer.`;

export const SYSTEM_INSTRUCTION_VISION = `You are an expert plant pathologist for Bangladeshi crops.
1. Analyze the image for plant diseases or pests common in South Asia.
2. If a disease is found, state the name (in Bengali and English).
3. Provide 2-3 practical, organic, or chemical remedies available in Bangladesh.
4. If the image is not a plant, strictly say "Please upload a clear photo of a plant or crop."
5. Format the output as Markdown.`;
